import logging
import re

import bleach

logger = logging.getLogger("isso")


class EmojiRenderer(object):
    EMOJI_MAP = {
        "smile": "😊",
        "smiley": "😃",
        "grin": "😁",
        "laughing": "😆",
        "satisfied": "😆",
        "innocent": "😇",
        "wink": "😉",
        "blush": "😊",
        "slight_smile": "🙂",
        "upside_down": "🙃",
        "relaxed": "☺️",
        "yum": "😋",
        "relieved": "😌",
        "heart_eyes": "😍",
        "kissing_heart": "😘",
        "kissing": "😗",
        "kissing_smiling_eyes": "😙",
        "kissing_closed_eyes": "😚",
        "stuck_out_tongue_winking_eye": "😜",
        "stuck_out_tongue_closed_eyes": "😝",
        "stuck_out_tongue": "😛",
        "money_mouth_face": "🤑",
        "nerd_face": "🤓",
        "sunglasses": "😎",
        "star_struck": "🤩",
        "partying_face": "🥳",
        "smirk": "😏",
        "unamused": "😒",
        "disappointed": "😞",
        "pensive": "😔",
        "worried": "😟",
        "confused": "😕",
        "slight_frown": "🙁",
        "frowning_face": "☹️",
        "persevere": "😣",
        "confounded": "😖",
        "tired_face": "😫",
        "weary": "😩",
        "triumph": "😤",
        "open_mouth": "😮",
        "scream": "😱",
        "fearful": "😨",
        "cold_sweat": "😰",
        "hushed": "😯",
        "frowning": "😦",
        "anguished": "😧",
        "cry": "😢",
        "disappointed_relieved": "😥",
        "drooling_face": "🤤",
        "sob": "😭",
        "sweat_smile": "😅",
        "sweat": "😓",
        "joy": "😂",
        "rofl": "🤣",
        "smiling_imp": "😈",
        "imp": "👿",
        "japanese_ogre": "👹",
        "japanese_goblin": "👺",
        "clown": "🤡",
        "shit": "💩",
        "hankey": "💩",
        "poop": "💩",
        "ghost": "👻",
        "alien": "👽",
        "space_invader": "👾",
        "robot": "🤖",
        "jack_o_lantern": "🎃",
        "smiley_cat": "😺",
        "smile_cat": "😸",
        "joy_cat": "😹",
        "heart_eyes_cat": "😻",
        "smirk_cat": "😼",
        "kissing_cat": "😽",
        "pouting_cat": "😾",
        "crying_cat_face": "😿",
        "scream_cat": "🙀",
        "open_hands": "👐",
        "raised_hands": "🙌",
        "clap": "👏",
        "wave": "👋",
        "+1": "👍",
        "thumbsup": "👍",
        "-1": "👎",
        "thumbsdown": "👎",
        "ok_hand": "👌",
        "v": "✌️",
        "crossed_fingers": "🤞",
        "point_up_2": "👆",
        "point_down": "👇",
        "point_left": "👈",
        "point_right": "👉",
        "fist_raised": "✊",
        "fist_oncoming": "👊",
        "fist_bump": "👊",
        "handshake": "🤝",
        "pray": "🙏",
        "rocket": "🚀",
        "star": "⭐",
        "star2": "🌟",
        "sparkles": "✨",
        "fire": "🔥",
        "boom": "💥",
        "collision": "💥",
        "zap": "⚡",
        "bulb": "💡",
        "thought_balloon": "💭",
        "anger": "💢",
        "exclamation": "❗",
        "question": "❓",
        "grey_exclamation": "❕",
        "grey_question": "❔",
        "warning": "⚠️",
        "zzz": "💤",
        "dash": "💨",
        "muscle": "💪",
        "dizzy": "💫",
        "speech_balloon": "💬",
        "white_check_mark": "✅",
        "x": "❌",
        "heavy_check_mark": "✔️",
        "heavy_multiplication_x": "✖️",
        "heart": "❤️",
        "broken_heart": "💔",
        "heartpulse": "💗",
        "heartbeat": "💓",
        "two_hearts": "💕",
        "sparkling_heart": "💖",
        "cupid": "💘",
        "gift_heart": "💝",
        "heart_exclamation": "❣️",
        "revolving_hearts": "💞",
        "heart_decoration": "💟",
        "love_letter": "💌",
        "kiss": "💋",
        "beers": "🍻",
        "beer": "🍺",
        "coffee": "☕",
        "tea": "🍵",
        "fork_and_knife": "🍴",
        "pizza": "🍕",
        "hamburger": "🍔",
        "fries": "🍟",
        "hotdog": "🌭",
        "taco": "🌮",
        "burrito": "🌯",
        "sushi": "🍣",
        "ramen": "🍜",
        "spaghetti": "🍝",
        "icecream": "🍦",
        "ice_cream": "🍨",
        "cake": "🍰",
        "birthday": "🎂",
        "cookie": "🍪",
        "candy": "🍬",
        "lollipop": "🍭",
        "chocolate_bar": "🍫",
        "popcorn": "🍿",
        "doughnut": "🍩",
        "apple": "🍎",
        "green_apple": "🍏",
        "pear": "🍐",
        "orange": "🍊",
        "lemon": "🍋",
        "banana": "🍌",
        "watermelon": "🍉",
        "grapes": "🍇",
        "strawberry": "🍓",
        "cherries": "🍒",
        "peach": "🍑",
        "melon": "🍈",
        "cherry_blossom": "🌸",
        "flower_playing_cards": "🎴",
        "tada": "🎉",
        "confetti_ball": "🎊",
        "gift": "🎁",
        "balloon": "🎈",
        "trophy": "🏆",
        "medal": "🏅",
        "sports_medal": "🏅",
        "first_place": "🥇",
        "second_place": "🥈",
        "third_place": "🥉",
        "checkered_flag": "🏁",
        "christmas_tree": "🎄",
        "fireworks": "🎆",
        "sparkler": "🎇",
        "jack_o_lantern": "🎃",
        "european_castle": "🏰",
        "house": "🏠",
        "house_with_garden": "🏡",
        "office": "🏢",
        "post_office": "🏣",
        "hospital": "🏥",
        "bank": "🏦",
        "hotel": "🏨",
        "convenience_store": "🏪",
        "school": "🏫",
        "department_store": "🏬",
        "factory": "🏭",
        "wedding": "💒",
        "church": "⛪",
        "mountain": "⛰️",
        "mountain_snow": "🏔️",
        "camping": "🏕️",
        "beach_umbrella": "🏖️",
        "desert": "🏜️",
        "desert_island": "🏝️",
        "national_park": "🏞️",
        "stadium": "🏟️",
        "house_buildings": "🏘️",
        "city_sunset": "🌆",
        "cityscape": "🌃",
        "night_with_stars": "🌃",
        "sunrise": "🌅",
        "sunrise_over_mountains": "🌄",
        "stars": "🌠",
        "sparkler": "🎇",
        "rainbow": "🌈",
        "ocean": "🌊",
        "volcano": "🌋",
        "milky_way": "🌌",
        "earth_africa": "🌍",
        "earth_americas": "🌎",
        "earth_asia": "🌏",
        "globe_with_meridians": "🌐",
        "new_moon": "🌑",
        "waxing_crescent_moon": "🌒",
        "first_quarter_moon": "🌓",
        "waxing_gibbous_moon": "🌔",
        "full_moon": "🌕",
        "waning_gibbous_moon": "🌖",
        "last_quarter_moon": "🌗",
        "waning_crescent_moon": "🌘",
        "crescent_moon": "🌙",
        "new_moon_with_face": "🌚",
        "full_moon_with_face": "🌝",
        "first_quarter_moon_with_face": "🌛",
        "last_quarter_moon_with_face": "🌜",
        "sun_with_face": "🌞",
        "thermometer": "🌡️",
        "sunny": "☀️",
        "mostly_sunny": "🌤️",
        "barely_sunny": "🌥️",
        "partly_sunny_rain": "🌦️",
        "rainy": "🌧️",
        "cloud": "☁️",
        "cloud_rain": "🌧️",
        "cloud_lightning": "🌩️",
        "cloud_tornado": "🌪️",
        "snowflake": "❄️",
        "snowman": "⛄",
        "snowman_with_snow": "☃️",
        "zap": "⚡",
        "umbrella": "☔",
        "umbrella_with_rain_drops": "☔",
        "phone": "📞",
        "telephone": "☎️",
        "fax": "📠",
        "pager": "📟",
        "tv": "📺",
        "radio": "📻",
        "computer": "💻",
        "minidisc": "💽",
        "floppy_disk": "💾",
        "cd": "💿",
        "dvd": "📀",
        "vhs": "📼",
        "camera": "📷",
        "camera_flash": "📸",
        "video_camera": "📹",
        "movie_camera": "🎥",
        "projector": "📽️",
        "microphone": "🎤",
        "headphones": "🎧",
        "music": "🎵",
        "musical_note": "🎵",
        "notes": "🎶",
        "musical_score": "🎼",
        "violin": "🎻",
        "drum": "🥁",
        "saxophone": "🎷",
        "trumpet": "🎺",
        "guitar": "🎸",
        "keyboard": "⌨️",
        "clapper": "🎬",
        "game_die": "🎲",
        "dart": "🎯",
        "bowling": "🎳",
        "video_game": "🎮",
        "slot_machine": "🎰",
        "8ball": "🎱",
        "art": "🎨",
        "performing_arts": "🎭",
        "circus_tent": "🎪",
        "ticket": "🎫",
        "clapper": "🎬",
        "footprints": "👣",
        "eyeglasses": "👓",
        "dark_sunglasses": "🕶️",
        "necktie": "👔",
        "shirt": "👕",
        "jeans": "👖",
        "dress": "👗",
        "kimono": "👘",
        "bikini": "👙",
        "womans_clothes": "👚",
        "purse": "👛",
        "handbag": "👜",
        "briefcase": "💼",
        "eyeglasses": "👓",
        "ribbon": "🎀",
        "lipstick": "💄",
        "nail_care": "💅",
        "ring": "💍",
        "gem": "💎",
        "crown": "👑",
        "tophat": "🎩",
        "mortar_board": "🎓",
        "construction_worker": "👷",
        "guardsman": "💂",
        "cop": "👮",
        "dancer": "💃",
        "dancers": "👯",
        "bride_with_veil": "👰",
        "person_with_blond_hair": "👱",
        "man_with_gua_pi_mao": "👲",
        "woman_with_turban": "👳",
        "older_man": "👴",
        "older_woman": "👵",
        "baby": "👶",
        "boy": "👦",
        "girl": "👧",
        "man": "👨",
        "woman": "👩",
        "angel": "👼",
        "princess": "👸",
        "prince": "🤴",
        "mrs_claus": "🤶",
        "santa": "🎅",
        "runner": "🏃",
        "walking": "🚶",
        "couple": "💑",
        "two_men_holding_hands": "👬",
        "two_women_holding_hands": "👭",
        "bow": "🙇",
        "information_desk_person": "💁",
        "no_good": "🙅",
        "ok_woman": "🙆",
        "raising_hand": "🙋",
        "massage": "💆",
        "haircut": "💇",
        "nail_care": "💅",
        "baby_bottle": "🍼",
        "sleeping": "😴",
        "zipper_mouth": "🤐",
        "money_with_wings": "💸",
        "calling": "📲",
        "raised_hand_with_fingers_splayed": "🖐️",
        "spock-hand": "🖖",
        "metal": "🤘",
        "fingers_crossed": "🤞",
        "vulcan_salute": "🖖",
        "write": "✍️",
        "writing_hand": "✍️",
        "point_right": "👉",
        "point_left": "👈",
        "point_up_2": "👆",
        "point_down": "👇",
        "fu": "🖕",
        "middle_finger": "🖕",
        "raised_hand": "✋",
        "raised_back_of_hand": "🤚",
        "palm_down_hand": "🤚",
        "palm_up_hand": "🤲",
        "open_hands": "👐",
        "raised_hands": "🙌",
        "clap": "👏",
        "point_up": "☝️",
        "wave": "👋",
        "ok_hand": "👌",
        "v": "✌️",
        "crossed_fingers": "🤞",
        "fist_raised": "✊",
        "fist_oncoming": "👊",
        "fist_bump": "👊",
        "handshake": "🤝",
        "pray": "🙏",
        "calendar": "📅",
        "date": "📅",
        "chart": "📈",
        "bar_chart": "📊",
        "chart_with_upwards_trend": "📈",
        "chart_with_downwards_trend": "📉",
        "notebook": "📓",
        "notebook_with_decorative_cover": "📔",
        "ledger": "📒",
        "books": "📚",
        "book": "📖",
        "page_facing_up": "📄",
        "scroll": "📜",
        "page_with_curl": "📃",
        "newspaper": "📰",
        "bookmark_tabs": "📑",
        "receipt": "🧾",
        "file_folder": "📁",
        "open_file_folder": "📂",
        "paperclip": "📎",
        "link": "🔗",
        "triangular_ruler": "📐",
        "straight_ruler": "📏",
        "pushpin": "📌",
        "round_pushpin": "📍",
        "scissors": "✂️",
        "paperclips": "📎",
        "black_nib": "✒️",
        "pencil2": "✏️",
        "paintbrush": "🖌️",
        "crayon": "🖍️",
        "lock": "🔒",
        "unlock": "🔓",
        "lock_with_ink_pen": "🔏",
        "closed_lock_with_key": "🔐",
        "key": "🔑",
        "mag_right": "🔎",
        "bulb": "💡",
        "flashlight": "🔦",
        "email": "📧",
        "envelope": "✉️",
        "inbox_tray": "📥",
        "outbox_tray": "📤",
        "package": "📦",
        "postbox": "📮",
        "mailbox": "📫",
        "mailbox_closed": "📪",
        "mailbox_with_mail": "📬",
        "mailbox_with_no_mail": "📭",
        "bell": "🔔",
        "no_bell": "🔕",
        "loud_sound": "🔊",
        "sound": "🔉",
        "mute": "🔇",
        "speaker": "🔈",
        "mega": "📣",
        "loudspeaker": "📢",
        "hourglass_flowing_sand": "⏳",
        "hourglass": "⌛",
        "watch": "⌚",
        "alarm_clock": "⏰",
        "timer": "⏲️",
        "clock": "🕐",
        "clock1": "🕐",
        "clock2": "🕑",
        "clock3": "🕒",
        "clock4": "🕓",
        "clock5": "🕔",
        "clock6": "🕕",
        "clock7": "🕖",
        "clock8": "🕗",
        "clock9": "🕘",
        "clock10": "🕙",
        "clock11": "🕚",
        "clock12": "🕛",
        "mountain_bicyclist": "🚵",
        "bicyclist": "🚴",
        "horse_racing": "🏇",
        "snowboarder": "🏂",
        "runner": "🏃",
        "surfer": "🏄",
        "swimmer": "🏊",
        "bath": "🛀",
        "ski": "🎿",
        "golf": "⛳",
        "basketball": "🏀",
        "basketball_player": "⛹️",
        "soccer": "⚽",
        "football": "🏈",
        "baseball": "⚾",
        "tennis": "🎾",
        "bowling": "🎳",
        "cricket": "🏏",
        "volleyball": "🏐",
        "rugby_football": "🏉",
        "car": "🚗",
        "red_car": "🚗",
        "taxi": "🚕",
        "blue_car": "🚙",
        "bus": "🚌",
        "trolleybus": "🚎",
        "racing_car": "🏎️",
        "police_car": "🚓",
        "fire_engine": "🚒",
        "ambulance": "🚑",
        "minibus": "🚐",
        "truck": "🚚",
        "articulated_lorry": "🚛",
        "tractor": "🚜",
        "bike": "🚲",
        "train": "🚃",
        "railway_car": "🚃",
        "bullettrain_side": "🚄",
        "bullettrain_front": "🚅",
        "metro": "🚇",
        "light_rail": "🚈",
        "station": "🚉",
        "tram": "🚊",
        "airplane": "✈️",
        "small_airplane": "🛩️",
        "flight_departure": "🛫",
        "flight_arrival": "🛬",
        "boat": "⛵",
        "sailboat": "⛵",
        "motor_boat": "🚤",
        "speedboat": "🚤",
        "passenger_ship": "🛳️",
        "ferry": "⛴️",
        "anchor": "⚓",
        "rocket": "🚀",
        "seat": "💺",
        "helicopter": "🚁",
        "steam_locomotive": "🚂",
        "traffic_light": "🚥",
        "vertical_traffic_light": "🚦",
        "construction": "🚧",
        "map": "🗺️",
        "moyai": "🗿",
        "statue_of_liberty": "🗽",
        "japan": "🗾",
        "rice_scene": "🎑",
        "ferris_wheel": "🎡",
        "roller_coaster": "🎢",
        "carousel_horse": "🎠",
        "building_construction": "🏗️",
        "foggy": "🌫️",
        "arrows_clockwise": "🔃",
        "arrows_counterclockwise": "🔄",
        "repeat": "🔁",
        "repeat_one": "🔂",
        "fast_forward": "⏩",
        "rewind": "⏪",
        "arrow_backward": "⬅️",
        "arrow_forward": "➡️",
        "arrow_up": "⬆️",
        "arrow_down": "⬇️",
        "arrow_up_small": "🔼",
        "arrow_down_small": "🔽",
        "left_right_arrow": "↔️",
        "arrow_up_down": "↕️",
        "leftwards_arrow_with_hook": "↩️",
        "arrow_right_hook": "↪️",
        "information_source": "ℹ️",
        "twisted_rightwards_arrows": "🔀",
        "mute": "🔇",
        "speaker": "🔈",
        "sound": "🔉",
        "loud_sound": "🔊",
        "no_entry": "⛔",
        "interrobang": "⁉️",
        "battery": "🔋",
        "electric_plug": "🔌",
        "mag": "🔍",
        "mag_right": "🔎",
        "shower": "🛁",
        "toilet": "🚽",
        "bath": "🛀",
        "wrench": "🔧",
        "hammer": "🔨",
        "nut_and_bolt": "🔩",
        "hocho": "🔪",
        "knife": "🔪",
        "gun": "🔫",
        "bomb": "💣",
        "pill": "💊",
        "syringe": "💉",
        "smoking": "🚬",
        "coffin": "⚰️",
        "speech_balloon": "💬",
        "thought_balloon": "💭",
        "triumph": "😤",
        "stuck_out_tongue": "😛",
        "stuck_out_tongue_winking_eye": "😜",
        "stuck_out_tongue_closed_eyes": "😝",
        "disappointed": "😞",
        "worried": "😟",
        "angry": "😠",
        "rage": "😡",
        "cry": "😢",
        "confounded": "😖",
        "persevere": "😣",
        "confused": "😕",
        "scream": "😱",
        "fearful": "😨",
        "disappointed_relieved": "😥",
        "hotsprings": "♨️",
        "tanabata_tree": "🎋",
        "flags": "🎏",
        "gift": "🎁",
        "confetti_ball": "🎊",
        "tada": "🎉",
        "dolls": "🎎",
        "wind_chime": "🎐",
        "crossed_flags": "🎌",
        "rice_scene": "🎑",
        "school_satchel": "🎒",
        "mortar_board": "🎓",
        "medal": "🏅",
        "reminder_ribbon": "🎗️",
        "toilet": "🚽",
        "door": "🚪",
        "bathtub": "🛁",
        "shower": "🚿",
        "smoking": "🚬",
        "signal_strength": "📶",
        "bell": "🔔",
        "calling": "📲",
        "vibration_mode": "📳",
        "mobile_phone_off": "📴",
        "file_folder": "📁",
        "open_file_folder": "📂",
        "link": "🔗",
        "radio_button": "🔘",
        "black_square_button": "🔲",
        "white_square_button": "🔳",
        "red_circle": "🔴",
        "large_blue_circle": "🔵",
        "small_orange_diamond": "🔸",
        "small_blue_diamond": "🔹",
        "small_red_triangle": "🔺",
        "small_red_triangle_down": "🔻",
        "large_orange_diamond": "🔶",
        "large_blue_diamond": "🔷",
        "white_circle": "⚪",
        "black_circle": "⚫",
        "white_check_mark": "✅",
        "ballot_box_with_check": "☑️",
        "heavy_check_mark": "✔️",
        "x": "❌",
        "negative_squared_cross_mark": "❎",
        "heavy_multiplication_x": "✖️",
        "curly_loop": "➰",
        "loop": "➿",
        "part_alternation_mark": "〽️",
        "eight_spoked_asterisk": "✳️",
        "eight_pointed_black_star": "✴️",
        "sparkle": "❇️",
        "copyright": "©️",
        "registered": "®️",
        "tm": "™️",
        "trademark": "™️",
        "bangbang": "‼️",
        "interrobang": "⁉️",
        "question": "❓",
        "grey_question": "❔",
        "exclamation": "❗",
        "grey_exclamation": "❕",
        "warning": "⚠️",
        "information_source": "ℹ️",
        "no_entry": "⛔",
        "arrow_double_up": "⏫",
        "arrow_double_down": "⏬",
        "fast_forward": "⏩",
        "rewind": "⏪",
        "arrow_backward": "⬅️",
        "arrow_forward": "➡️",
        "arrow_up": "⬆️",
        "arrow_down": "⬇️",
        "arrow_up_down": "↕️",
        "left_right_arrow": "↔️",
        "arrow_up_down": "↕️",
        "left_right_arrow": "↔️",
        "arrow_right_hook": "↪️",
        "leftwards_arrow_with_hook": "↩️",
        "arrow_heading_up": "⤴️",
        "arrow_heading_down": "⤵️",
        "arrows_clockwise": "🔃",
        "arrows_counterclockwise": "🔄",
        "back": "🔙",
        "end": "🔚",
        "on": "🔛",
        "soon": "🔜",
        "top": "🔝",
        "keycap_ten": "🔟",
        "one_two_three_four": "🔢",
        "zero": "0️⃣",
        "one": "1️⃣",
        "two": "2️⃣",
        "three": "3️⃣",
        "four": "4️⃣",
        "five": "5️⃣",
        "six": "6️⃣",
        "seven": "7️⃣",
        "eight": "8️⃣",
        "nine": "9️⃣",
        "hash": "#️⃣",
        "keycap_star": "*️⃣",
        "capital_abcd": "🔠",
        "abcd": "🔡",
        "symbols": "🔣",
        "abc": "🔤",
    }

    EMOJI_PATTERN = re.compile(r":([a-zA-Z0-9_+-]+):")

    def __init__(self, enabled=True):
        self.enabled = enabled

    def _replace_emoji(self, match):
        name = match.group(1).lower()
        return self.EMOJI_MAP.get(name, match.group(0))

    def render(self, text):
        if not self.enabled:
            return text
        if ":" not in text:
            return text
        return self.EMOJI_PATTERN.sub(self._replace_emoji, text)


class Sanitizer(object):
    # pattern to match a valid class attribute for code tags
    code_language_pattern = re.compile(r"^language-[a-zA-Z0-9]{1,20}$")

    @staticmethod
    def allow_attribute_class(tag, name, value):
        return name == "class" and bool(Sanitizer.code_language_pattern.match(value))

    def __init__(self, elements, attributes):
        # attributes found in Sundown's HTML serializer [1]
        # - except for <img> tag, because images are not generated anyway.
        # - sub and sup added
        #
        # [1] https://github.com/vmg/sundown/blob/master/html/html.c
        self.elements = [
            "a",
            "p",
            "hr",
            "br",
            "ol",
            "ul",
            "li",
            "pre",
            "code",
            "blockquote",
            "del",
            "ins",
            "strong",
            "em",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "sub",
            "sup",
            "table",
            "thead",
            "tbody",
            "th",
            "td",
        ] + elements

        # allowed attributes for tags
        self.attributes = {"table": ["align"], "a": ["href"], "code": Sanitizer.allow_attribute_class, "*": attributes}

    def sanitize(self, text):
        clean_html = bleach.clean(text, tags=self.elements, attributes=self.attributes, strip=True)

        def set_links(attrs, new=False):
            # Linker can misinterpret text as a domain name and create new invalid links.
            # To prevent this, we only allow existing links to be modified.
            if new:
                return None

            href_key = (None, "href")

            if href_key not in attrs:
                return attrs
            if attrs[href_key].startswith("mailto:"):
                return attrs

            rel_key = (None, "rel")
            rel_values = [val for val in attrs.get(rel_key, "").split(" ") if val]

            for value in ["nofollow", "noopener"]:
                if value not in [rel_val.lower() for rel_val in rel_values]:
                    rel_values.append(value)

            attrs[rel_key] = " ".join(rel_values)
            return attrs

        linker = bleach.linkifier.Linker(callbacks=[set_links])
        return linker.linkify(clean_html)


class Markup(object):
    def __init__(self, conf):
        conf_markup = conf.section("markup")

        if conf_markup.has_option("renderer") and conf_markup.get("renderer") == "mistune":
            from isso.html.mistune import MistuneMarkdown

            self.parser = MistuneMarkdown(conf.section("markup.mistune"))
            logging.info("Using Mistune as Markdown rendering engine")
        elif not conf_markup.has_option("renderer") or conf_markup.get("renderer") == "misaka":
            # We do not want to depend on Misaka unless it is actually used
            from isso.html.misaka import MisakaMarkdown

            self.parser = MisakaMarkdown(conf)
            logging.warning(
                "Misaka has been deprecated. Please switch to Mistune for Markdown rendering before the next release."
            )
        else:
            logging.fatal(
                "The `renderer` configuration option is set to an unknown value: %s. Set to either `mistune` or `misaka`.",
                conf_markup.get("renderer"),
            )
            raise ValueError("Invalid renderer value: %s. Set to either `mistune` or `misaka`." % conf_markup.get("renderer"))

        emoji_enabled = True
        if conf_markup.has_option("emoji-enabled"):
            emoji_enabled = conf_markup.getboolean("emoji-enabled")
        self.emoji_renderer = EmojiRenderer(enabled=emoji_enabled)

        # Filter out empty strings:
        allowed_elements = [x for x in conf_markup.getlist("allowed-elements") if x]
        allowed_attributes = [x for x in conf_markup.getlist("allowed-attributes") if x]

        # If images are allowed, source element should be allowed as well
        if "img" in allowed_elements and "src" not in allowed_attributes:
            allowed_attributes.append("src")
        self.sanitizer = Sanitizer(allowed_elements, allowed_attributes)

    def render(self, text):
        text_with_emojis = self.emoji_renderer.render(text)
        return self.sanitizer.sanitize(self.parser.render(text_with_emojis))
