version: 2.1

general:
  branches:
    only:
     - master # list of branches to build
     - circleci
     - /feature-.*/ # or regexes

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

workflows:
  default:
    jobs:
      - nosetests


jobs:
  nosetests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: "ls -la ~ && ls -la ."
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "isso/tests/requirements-test.txt" }}
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/isso/tests/
          pip-dependency-file: requirements-test.txt
      - run:
          name: Install isso in editable mode
          command: pip install -e .
      - run:
          name: Run nosetests
          command: nosetests isso/
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "isso/tests/requirements-test.txt" }}
          paths:
            - "venv"
