version: 2.1

general:
  branches:
    only:
     - master # list of branches to build
     - circleci
     - /feature-.*/ # or regexes

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1.0

workflows:
  default:
    jobs:
      - nosetests
      - flakes
      - docs
      - css


jobs:
  nosetests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: "ls -la ~ && ls -la ."
      - restore_cache:
          key: pip-pkgs-v1-{{ .Branch }}-{{ checksum "isso/tests/requirements-test.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r isso/tests/requirements-test.txt
      - save_cache:
          key: pip-pkgs-v1-{{ .Branch }}-{{ checksum "isso/tests/requirements-test.txt" }}
          paths:
            - "~/venv"
      - run:
          name: Install isso in editable mode
          command: |
            . ~/venv/bin/activate
            pip install -e .
      - run:
          name: Run nosetests with coverage
          command: |
            . ~/venv/bin/activate
            nosetests --with-doctest --with-coverage --cover-package=isso isso/

  flakes:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: pip-pkgs-v1-{{ .Branch }}-{{ checksum "isso/tests/requirements-test.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r isso/tests/requirements-test.txt
      - run:
          name: Run flake8
          # FIXME Allowed to fail until formatting is fixed
          command: |
            . venv/bin/activate
            flake8 . --count --max-line-length=127 --show-source --statistics || /bin/true
      - save_cache:
          key: pip-pkgs-v1-{{ .Branch }}-{{ checksum "isso/tests/requirements-test.txt" }}
          paths:
            - "~/venv"

  css:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install node-sass
      - run: ./node_modules/node-sass/bin/node-sass --no-cache docs/_static/css/site.scss docs/_static/css/site.css
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules
      - store_artifacts:
          path: docs/_static/css/site.css
          destination: site.css

  docs:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: pip-pkgs-v1-{{ .Branch }}-{{ checksum "isso/tests/requirements-test.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r isso/tests/requirements-test.txt
      - save_cache:
          key: pip-pkgs-v1-{{ .Branch }}-{{ checksum "isso/tests/requirements-test.txt" }}
          paths:
            - "~/venv"
      - run:
          name: Install isso in editable mode
          command: |
            . ~/venv/bin/activate
            pip install -e .
      - run:
          name: Compile docs using sphinx
          command: |
            . ~/venv/bin/activate
            sphinx-build -b dirhtml docs/ docs/_build/html
