# Download puppeteer assets
# This image should be tagged as "isso-js-puppeteer"

# Avoid triggering a re-download of its puppeteer assets if at all possible

# Note: Keep (alpine) base image in sync with other dockerfiles to avoid
# duplication
FROM docker.io/node:current AS isso-js-puppeteer
WORKDIR /src/

# Installing puppeteer will take some time as it pulls in
# a ~400Mb headless chrome file
RUN npm install puppeteer

# Example of use:
#
# docker build -f docker/Dockerfile-js-puppeteer -t isso-js-puppeteer .

# vim: set filetype=dockerfile
