.TH ISSO 1 "December 22, 2013"
.SH NAME
isso \- web commenting system
.br
.br
This program is documented in HTML format.
The files are available under the directory /usr/share/doc/isso/
.SH AUTHOR
Isso was written by Martin Zimmermann.
.PP
This manual page was written by Federico Ceratto <federico.ceratto@gmail.com>,
for the Debian project (and may be used by others).
