name: sphinx documentation

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/documentation.yml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/documentation.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: sudo apt install python3-sphinx

      - name: Check docs
        # TODO: -W turns warnings into errors
        run: make site
